apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auction-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auction-postgres
  serviceName: "auction-postgres"
  template:
    metadata:
      labels:
        app: auction-postgres
    spec:
      containers:
        - name: auction-postgres
          image: postgres:16-alpine
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: auction-configmap
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: auction-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auction-secret
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: auction-db
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: auction-db
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "local-path"
        resources:
          requests:
            storage: 1Gi